import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-white text-black m-0 p-0 ">
        <Navbar/>
        <main className="bg-white text-black w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
